spring:
  datasource:
    url: ${DB_URL}
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: debug
server:
  port: 8080